"""newnewenwenwenw

Revision ID: 1b87286e3d29
Revises: 0c61d29cb77e
Create Date: 2024-06-04 00:14:37.893246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b87286e3d29'
down_revision: Union[str, None] = '0c61d29cb77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scripts', 'categories', ['category_id'], ['category_id'])
    op.drop_column('scripts', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('category_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_column('scripts', 'category_id')
    # ### end Alembic commands ###
