"""scrits table rework_V.0.2

Revision ID: 1bc40a60cfd3
Revises: d339afbd452a
Create Date: 2024-05-29 21:59:31.062881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc40a60cfd3'
down_revision: Union[str, None] = 'd339afbd452a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE scripts ALTER COLUMN category_name TYPE INTEGER USING category_name::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE scripts ALTER COLUMN category_name TYPE VARCHAR USING category_name::varchar')
    # ### end Alembic commands ###
