"""HISTOYTY table update

Revision ID: 4f747e092340
Revises: 1b87286e3d29
Create Date: 2024-06-06 01:42:44.613695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f747e092340'
down_revision: Union[str, None] = '1b87286e3d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'time')
    # ### end Alembic commands ###
