"""ADMIN TABEL REWORK 

Revision ID: 67f302798784
Revises: 18ce21f16472
Create Date: 2024-06-09 23:10:41.465471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f302798784'
down_revision: Union[str, None] = '18ce21f16472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('account_atatus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'account_atatus')
    # ### end Alembic commands ###
