"""ADMIN_TABLE

Revision ID: 785498add58d
Revises: 4f747e092340
Create Date: 2024-06-06 14:44:42.801532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785498add58d'
down_revision: Union[str, None] = '4f747e092340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('qualification_level', sa.Integer(), nullable=True))
    op.drop_constraint('admin_scripts_id_fkey', 'admin', type_='foreignkey')
    op.drop_column('admin', 'scripts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('scripts_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('admin_scripts_id_fkey', 'admin', 'scripts', ['scripts_id'], ['scripts_id'])
    op.drop_column('admin', 'qualification_level')
    # ### end Alembic commands ###
