"""ADMIN TABEL REWORK22 

Revision ID: 846f47897e15
Revises: b0e128438930
Create Date: 2024-06-09 23:13:16.327118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846f47897e15'
down_revision: Union[str, None] = 'b0e128438930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('account_status', sa.Boolean(), nullable=True))
    op.drop_column('admin', 'account_atatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('account_atatus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('admin', 'account_status')
    # ### end Alembic commands ###
