"""COMMNT&QISETP REWORK

Revision ID: 8f533df7c6cb
Revises: 1bc40a60cfd3
Create Date: 2024-05-29 23:50:23.882901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f533df7c6cb'
down_revision: Union[str, None] = '1bc40a60cfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_4', sa.String(), nullable=True))
    op.add_column('question', sa.Column('option_4', sa.String(), nullable=True))
    op.alter_column('question', 'question',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute('ALTER TABLE question ALTER COLUMN plus_point TYPE INTEGER USING plus_point::integer')
    op.execute('ALTER TABLE question ALTER COLUMN minus_point TYPE INTEGER USING minus_point::integer')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE question ALTER COLUMN minus_point TYPE VARCHAR USING minus_point::varchar')
    op.execute('ALTER TABLE question ALTER COLUMN plus_point TYPE VARCHAR USING plus_point::varchar')
    op.alter_column('question', 'question',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('question', 'option_4')
    op.drop_column('comment', 'comment_4')
    # ### end Alembic commands ###
