"""ADMIN_TABLE_rework

Revision ID: cef45b4013ef
Revises: 785498add58d
Create Date: 2024-06-06 15:18:25.633741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef45b4013ef'
down_revision: Union[str, None] = '785498add58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'admin_name')
    # ### end Alembic commands ###
