"""ADMIN TABEL REWORK22333ee 

Revision ID: f52405d928a1
Revises: ecb0f0355016
Create Date: 2024-06-10 02:26:29.431800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52405d928a1'
down_revision: Union[str, None] = 'ecb0f0355016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['admin_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
